Update and Optimize Dockerfile
add multi-stage building

diff --git a/contrib/docker/Dockerfile b/contrib/docker/Dockerfile
--- a/contrib/docker/Dockerfile
+++ b/contrib/docker/Dockerfile
@@ -1,31 +1,38 @@
-# 611 (SixEleven) docker iamge
-
-FROM debian:stretch
+# 611 (SixEleven) Coin Wallet on Docker
+FROM debian:stretch AS builder
 
 MAINTAINER 611project
 ENV REFRESHED_AT 20200517
 
+# grab the latest 611 source code from git, compile, install and clean up
+RUN set -ex; \
+	apt-get update ; \
+        apt-get upgrade ; \
+	# install dependencies
+	apt-get install -y --no-install-recommends ca-certificates wget \
+		build-essential dirmngr libboost-all-dev zlib1g-dev git ; \
+	# compile and install 611
+	cd /usr/src ; \
+	git clone https://github.com/611project/sixeleven.git sixeleven ; \
+	cd sixeleven/contrib ; \
+	./build-static-with-db48.sh ; \
+	strip ../build/611d
+
+FROM debian:stretch
+
 RUN groupadd -r sixeleven && useradd -r -m -g sixeleven sixeleven
 
-# grab the latest 611 source code from git, compile, install and clean up
-RUN set -ex \
-	&& apt-get update \
+RUN set -ex; \
+	apt-get update ; \
+	apt-get upgrade ; \
 	# install dependencies
-	&& apt-get install -y --no-install-recommends ca-certificates wget \
-		build-essential libssl1.0-dev gnupg dirmngr libboost-all-dev zlib1g-dev git gosu \
-	# compile and install 611
-	&& cd /usr/src \
-	&& git clone https://github.com/611project/sixeleven.git sixeleven \
-	&& cd sixeleven/contrib \
-	&& ./build-static-with-db48.sh \
-	&& cp ../src/611d /usr/local/bin \
-	&& strip /usr/local/bin/611d \
+	apt-get install -y --no-install-recommends ca-certificates \
+		libgcc1 zlib1g gosu ; \
 	# cleanup
-	&& cd ../.. && rm -rf /usr/src/sixeleven \
-	&& apt-get -y purge build-essential libssl1.0-dev gnupg dirmngr libboost-all-dev zlib1g-dev git \
-	&& apt-get -y autoremove \
-	&& apt-get clean \
-	&& rm -rf /var/lib/apt/lists/*
+	apt-get clean ; \
+	rm -rf /var/lib/apt/lists/*
+
+COPY --from=builder /usr/src/sixeleven/build/611d /usr/local/bin/
 
 ENV SIXELEVEN_DATA /sixeleven
 RUN mkdir $SIXELEVEN_DATA \
